### PR TITLE
Add value lists

### PR DESCRIPTION
**Pull request by daren-thomas**
This pull request implements the functionality to add CSV files as `GH_ValueList`  parameters to a BADGERFILE.

Check out the `examples/planets/planets.json` on how to set that up. The first column in the CSV file is used to display the dropdown list. The output is a json dict of the selected row, indexed by column name. Each value is converted to float if possible (this could maybe be improved in a future PR).

To test, run `honey-badger.exe -i examples\planets\planets.json`. Run Grasshopper and add the two planet things to the canvas. Add a panel for the output and link the three together. Spend some time exploring our solar system!

### CODE REVIEW

**Comment by christophwaibel** [comment]
I am getting "Object reference not set to an instance of an object" errors when trying to build any json. I re-compiled honey-badger.exe, still not working. Am I missing something?

image

**Comment by daren-thomas** [comment]
I get that too! Augh! Looking into it. In the meantime: `ipy.exe honey-badger.py -i examples\planets\planets.json` will work if you have `ipy.exe` in your PATH.

**Comment by christophwaibel** [comment]
Doesn't work for me either. It says, it is missing `honey-badger-runtime.dll`. Tried to re-compile with `make-honey-badger.bat`, but it also says `Object Reference not set to an instance of an object`

This is the full error log when trying to build with ipy.exe:

`C:\Program Files\IronPython 2.7>ipy.exe C:\Users\chwaibel\Documents\GitHub\honey-badger\honey-badger.py -i C:\Users\chwaibel\Documents\GitHub\honey-badger\examples\planets\planets.json
Traceback (most recent call last):
  File "C:\Users\chwaibel\Documents\GitHub\honey-badger\honey-badger.py", line 27, in <module>
  File "C:\Users\chwaibel\Documents\GitHub\honey-badger\parameter_compiler.py", line 18, in <module>
IOError: System.IO.IOException: file does not exist: C:\Users\chwaibel\Documents\GitHub\honey-badger\honey-badger-runtime\bin\honey-badger-runtime.dll
   at IronPython.Runtime.ClrModule.AddReferenceToFileAndPath(CodeContext context, String file)
   at IronPython.Runtime.ClrModule.AddReferenceToFileAndPath(CodeContext context, String[] files)
   at Microsoft.Scripting.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run4[T0,T1,T2,T3,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at IronPython.Compiler.Ast.CallExpression.Invoke1Instruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
   at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
   at IronPython.Runtime.PythonContext.InitializeModule(String fileName, ModuleContext moduleContext, ScriptCode scriptCode, ModuleOptions options)
   at IronPython.Runtime.Importer.LoadModuleFromSource(CodeContext context, String name, String path)
   at IronPython.Runtime.Importer.LoadFromDisk(CodeContext context, String name, String fullName, String str)
   at IronPython.Runtime.Importer.ImportFromPathHook(CodeContext context, String name, String fullName, List path, Func`5 defaultLoader)
   at IronPython.Runtime.Importer.ImportFromPath(CodeContext context, String name, String fullName, List path)
   at IronPython.Runtime.Importer.ImportTopAbsolute(CodeContext context, String name)
   at IronPython.Runtime.Importer.ImportModule(CodeContext context, Object globals, String modName, Boolean bottom, Int32 level)
   at IronPython.Modules.Builtin.__import__(CodeContext context, String name, Object globals, Object locals, Object fromlist, Int32 level)
   at IronPython.Runtime.Importer.ImportLightThrow(CodeContext context, String fullName, PythonTuple from, Int32 level)
   at Microsoft.Scripting.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
   at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
   at IronPython.Hosting.PythonCommandLine.RunFileWorker(String fileName)
   at IronPython.Hosting.PythonCommandLine.RunFile(String fileName)`

**Comment by daren-thomas** [comment]
ah. honey-badger-runtime.dll... that's an output of the c# solution. let's see if i can add that to the repo...

**Comment by daren-thomas** [comment]
@christophwaibel ok, it should work now. note that the `honey-badger.exe` feature was removed - you'll have to run it with `ipy honey-badger.py` instead.

**Comment by christophwaibel** [comment]
I can build successfully with `ipy.exe`, but now I'm getting these errors when opening Grasshopper. 

image

**Comment by daren-thomas** [comment]
@christophwaibel oops. Sorry about that. I've fixed it.

**Pull request merged**
